### ISSUE TITLE
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2.4 compiler:

### ISSUE THREAD

**Issue by uzirthapa** [syonip/flutter_publitio#4]

**Comment by chanmaoinc** [comment]
Same issue.
@uzirthapa Did you find out any solution?

**Comment by syonip** [comment]
Hi,
I would advise to think twice before using this package for a **serverless** app, as it includes storing the key and secret on the client.
If you're going for a serverless solution, you can check out my more recent post here, which uses firebase: https://www.learningsomethingnew.com/flutter-video-upload-firebase-storage-hls.

Cheers.

**Comment by chanmaoinc** [comment]
@syonip  We are not using for a serverless app, just common. The problem is we can not build successfully.

**Comment by syonip** [comment]
In that case you should probably upload files to your server first, and upload to publitio from there.
The reason is that the same credentials you put on the client can be used by someone to delete all your files.

**Comment by uzirthapa** [comment]
Yes I solved the issue by using Xcode 11.2 downloaded from Apple developers website.

**Comment by chanmaoinc** [comment]
Thanks @uzirthapa .

@syonip , We are using this plugin in Android very well, the only problem is the failed building in
iOS. I'm using Xcode 11.5, is there any possible to fix the issue for Xcode 11.5 ?  
Thanks so much.

**Comment by anthonycmeow** [comment]
@uzirthapa How about Xcode 11.5? 
@chanmaoinc  I have same issue in Xcode 11.5
